CREATE TABLE CLIENT(
	idClient INTEGER GENERATED BY DEFAULT AS IDENTITY (start with 1),
	nom varchar(20),
	PRIMARY KEY (idClient)
);

CREATE TABLE COMPTE_BANCAIRE(
	iban varchar(32),
	proprietaire VARCHAR(50),
	swift_code varchar(8),
	principal INTEGER,
	PRIMARY KEY (iban)
);



CREATE TABLE COMPTE_CLIENT(
  idClient INTEGER ,
  iban varchar(20),
  PRIMARY KEY (idClient, iban),
  FOREIGN KEY (idClient) REFERENCES CLIENT(idClient),
  FOREIGN KEY (iban) REFERENCES COMPTE_BANCAIRE(iban)
);



create TABLE ASSURANCE(
    numeroAssurance INTEGER,
    typeAssurance varchar(50),
    dateSouscription DATE,
    dateAnniversaire DATE,
    datePrevelement DATE,
    immatriculation varchar(10),
    bonusMalus INTEGER,
    adresseAssure varchar(50),
    valeurCouverture INTEGER,
    PRIMARY KEY (numeroAssurance)
  );

  create TABLE PERSONNE_MORALE(
    SIREN varchar(9),
    nom varchar(20),
    idClient INTEGER,
    PRIMARY KEY (SIREN),
    FOREIGN KEY (idClient) REFERENCES CLIENT(idClient)
  );

  create TABLE PERSONNE_PHYSIQUE(
    nom varchar(20),
    prenom varchar(20),
    dateNaissance DATE,
    idClient INTEGER,
    PRIMARY KEY (idClient),
    FOREIGN KEY (idClient) REFERENCES CLIENT(idClient)
  );

  create TABLE CLIENT_ASSURANCE(
    idClient INTEGER ,
    numeroAssurance INTEGER ,
    PRIMARY KEY (idClient, numeroAssurance),
    FOREIGN KEY (idClient) REFERENCES CLIENT(idClient),
    FOREIGN KEY (numeroAssurance) REFERENCES ASSURANCE(numeroAssurance)
  );

create TABLE ECHEANCES(
    idEcheance INTEGER GENERATED BY DEFAULT AS IDENTITY (start with 1),
    prix INTEGER,
    dateEmission DATE,
    datePaiement DATE,
    dateEmissionFacture DATE,
    PRIMARY KEY (idEcheance)
);

create TABLE CONTACT(
    typeContact varchar(20),
    valeur varchar(20),
    idContact INTEGER GENERATED BY DEFAULT AS IDENTITY (start with 1),
    PRIMARY KEY (idContact)
  );

create TABLE ASSURANCES_ECHEANCES(
    idEcheance INTEGER,
    numeroAssurance INTEGER,
    PRIMARY KEY (idEcheance, numeroAssurance),
    FOREIGN KEY (idEcheance) REFERENCES ECHEANCES(idEcheance),
    FOREIGN KEY (numeroAssurance) REFERENCES ASSURANCE(numeroAssurance)
);

CREATE TABLE CONTACT_CLIENT(
  idClient INTEGER ,
  idContact INTEGER,
  PRIMARY KEY (idClient, idContact),
  FOREIGN KEY (idClient) REFERENCES CLIENT(idClient),
  FOREIGN KEY (idContact) REFERENCES CONTACT(idContact)
);